name: Publish package to pub.dev
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache 
          cat <<EOF > ~/.pub-cache/credentials.json
          ${{ secrets.CREDENTIAL_JSON }}
          EOF
      - name: Publish package
        run: pub publish -f
